Repository DeepKernelLabs/airflow-tools, pull requests merged in 2024-04, with the labels that each got.

#39 Add logo to project
  README.md
  media/images/logo.webp
Labels: documentation

#43 fix: solve problem compression with jsonl and gzip (http_to_data_lake)
  poetry.lock
  src/airflow_tools/providers/http_to_data_lake/operators/http_to_data_lake.py
  tests/unit/test_compression.py
Labels: bug

#45 Feature: Add create_file_on_success to Filesystem operators
  poetry.lock
  pyproject.toml
  src/airflow_tools/_version.py
  src/airflow_tools/providers/filesystem/operators/filesystem.py
Labels: enhancement

#48 Fix(LocalFilesystem): Fix check_file and check_prefix methods
  poetry.lock
  pyproject.toml
  src/airflow_tools/_version.py
  src/airflow_tools/filesystems/impl/local_filesystem.py
Labels: bug
